# .github/workflows/simple-test.yml

name: Prosty Test Workflow

on:
  push:
    branches:
      - ino_dev
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Wypisz powitanie
        run: echo "ğŸ‰ Workflow dla gaÅ‚Ä™zi ino_dev zostaÅ‚ pomyÅ›lnie uruchomiony!"
